//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobiSchool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pergunta
    {
        public int Id { get; set; }
        public string Enunciado { get; set; }
        public string Comentario { get; set; }
        public int DisciplinaId { get; set; }
        public int TipoDificuldadeId { get; set; }
    
        public virtual Disciplina Disciplina { get; set; }
        public virtual TipoDificuldade TipoDificuldade { get; set; }
        public virtual Resposta Resposta { get; set; }
    }
}
